import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../../core/services/api.service';

@Component({
  selector: 'app-admin-admissions',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <main class="admissions-page"><header><div><p class="eyebrow">Admin portal</p><h1>Admission applications</h1><p class="muted">Review, approve, or reject student applications.</p></div><div class="filters"><input [(ngModel)]="search" (input)="loadAdmissions()" placeholder="Search applications"><select [(ngModel)]="status" (change)="loadAdmissions()"><option value="">All statuses</option><option>PENDING</option><option>APPROVED</option><option>REJECTED</option></select></div></header><div *ngIf="loading" class="state">Loading admissions...</div><div *ngIf="!loading && errorMessage" class="state error">{{ errorMessage }} <button (click)="loadAdmissions()">Retry</button></div><section *ngIf="!loading && !errorMessage" class="table-card"><div *ngIf="!admissions.length" class="state">No applications found.</div><div class="table-wrap" *ngIf="admissions.length"><table><thead><tr><th>Application</th><th>Student</th><th>Class</th><th>Submitted</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr *ngFor="let application of admissions"><td><strong>{{ application.applicationId }}</strong><small>{{ application.email }}</small></td><td>{{ application.firstName }} {{ application.lastName }}<small>{{ application.phone }}</small></td><td>{{ application.applyingClass }}</td><td>{{ application.createdAt | date:'mediumDate' }}</td><td><span class="status" [class.pending]="application.status === 'PENDING'" [class.approved]="application.status === 'APPROVED'" [class.rejected]="application.status === 'REJECTED'">{{ application.status }}</span></td><td><button class="view" (click)="selected = application">View</button><button *ngIf="application.status === 'PENDING'" class="approve" (click)="approve(application)">Approve</button><button *ngIf="application.status === 'PENDING'" class="reject" (click)="reject(application)">Reject</button></td></tr></tbody></table></div></section><div *ngIf="selected" class="modal-backdrop" (click)="selected = null"><section class="modal" (click)="$event.stopPropagation()"><button class="close" (click)="selected = null">×</button><h2>{{ selected.firstName }} {{ selected.lastName }}</h2><p class="muted">{{ selected.applicationId }} · {{ selected.status }}</p><dl><div><dt>Applying for</dt><dd>{{ selected.applyingClass }}</dd></div><div><dt>Previous school</dt><dd>{{ selected.previousSchool || 'Not provided' }}</dd></div><div><dt>Parent / guardian</dt><dd>{{ selected.guardianName || selected.fatherName || selected.motherName || 'Not provided' }}</dd></div><div><dt>Address</dt><dd>{{ selected.address }}, {{ selected.city }}, {{ selected.state }} {{ selected.pinCode }}</dd></div><div *ngIf="selected.rejectionReason"><dt>Rejection reason</dt><dd>{{ selected.rejectionReason }}</dd></div></dl></section></div></main>
  `,
  styles: [`
    :host{display:block;min-height:100vh}.admissions-page{padding:34px;background:#f5f7fb;min-height:100vh;color:#172033}header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:24px}.eyebrow{margin:0 0 5px;color:#2563eb;font-size:12px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}h1{margin:0}.muted,small{color:#64748b}.filters{display:flex;gap:10px}.filters input,.filters select{border:1px solid #cbd5e1;border-radius:8px;padding:10px;font:inherit;background:#fff}.table-card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse;min-width:760px}th,td{padding:15px 16px;text-align:left;border-bottom:1px solid #eef2f7;font-size:14px}th{background:#f8fafc;color:#64748b;font-size:12px;text-transform:uppercase;letter-spacing:.05em}td small{display:block;margin-top:4px}.status{display:inline-block;padding:5px 8px;border-radius:99px;font-size:11px;font-weight:800;background:#e2e8f0}.status.pending{background:#fef3c7;color:#92400e}.status.approved{background:#dcfce7;color:#166534}.status.rejected{background:#fee2e2;color:#991b1b}button{border:0;border-radius:6px;padding:7px 9px;margin-right:5px;font-weight:700;cursor:pointer}.view{background:#eff6ff;color:#2563eb}.approve{background:#dcfce7;color:#166534}.reject{background:#fee2e2;color:#991b1b}.state{padding:45px;text-align:center;color:#64748b}.error{color:#b91c1c}.modal-backdrop{position:fixed;inset:0;display:grid;place-items:center;padding:20px;background:rgba(15,23,42,.45);z-index:10}.modal{position:relative;width:min(560px,100%);padding:28px;background:#fff;border-radius:12px}.close{position:absolute;right:14px;top:12px;background:#f1f5f9;font-size:20px}dl{display:grid;gap:14px}dl div{display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid #f1f5f9;padding-bottom:10px}dt{color:#64748b}dd{margin:0;text-align:right;font-weight:600}@media(max-width:760px){.admissions-page{padding:24px 14px}header{display:block}.filters{margin-top:18px;flex-direction:column}.filters input,.filters select{width:100%;box-sizing:border-box}}
  `]
})
export class AdminAdmissionManagementComponent implements OnInit {
  admissions: any[] = []; search = ''; status = ''; loading = true; errorMessage = ''; selected: any = null;
  constructor(private apiService: ApiService, private changeDetectorRef: ChangeDetectorRef) {}
  ngOnInit(): void { this.loadAdmissions(); }
  loadAdmissions(): void { this.loading = true; this.errorMessage = ''; const params: Record<string, string> = {}; if (this.search) params['search'] = this.search; if (this.status) params['status'] = this.status; this.apiService.getAdminAdmissions(params).subscribe({ next: response => { this.admissions = response.data?.admissions || []; this.loading = false; this.changeDetectorRef.markForCheck(); }, error: error => { console.error('Admissions error:', error); this.loading = false; this.errorMessage = 'Unable to load admission applications.'; this.changeDetectorRef.markForCheck(); } }); }
  approve(application: any): void { this.apiService.approveAdminAdmission(application._id).subscribe({ next: () => this.loadAdmissions(), error: error => { this.errorMessage = error.error?.message || 'Unable to approve application.'; this.changeDetectorRef.markForCheck(); } }); }
  reject(application: any): void { const reason = window.prompt('Reason for rejection:'); if (reason === null) return; this.apiService.rejectAdminAdmission(application._id, reason).subscribe({ next: () => this.loadAdmissions(), error: error => { this.errorMessage = error.error?.message || 'Unable to reject application.'; this.changeDetectorRef.markForCheck(); } }); }
}
