import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../../../core/services/api.service';

@Component({
  selector: 'app-student-admission',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  template: `
    <main class="admission-page"><section class="admission-card"><button class="back" (click)="router.navigate(['/student/dashboard'])">← Dashboard</button><p class="eyebrow">Student portal</p><h1>Admission application</h1><p class="muted">Complete the form carefully. Your application will start in Pending status.</p><div *ngIf="errorMessage" class="alert error">{{ errorMessage }}</div><div *ngIf="successMessage" class="alert success">{{ successMessage }}</div><form [formGroup]="form" (ngSubmit)="submit()"><fieldset><legend>Personal information</legend><div class="grid"><label>Full name *<input formControlName="fullName"></label><label>Date of birth *<input type="date" formControlName="dateOfBirth"></label><label>Gender *<select formControlName="gender"><option value="">Choose gender</option><option>Male</option><option>Female</option><option>Other</option></select></label><label>Blood group<input formControlName="bloodGroup"></label><label>Phone *<input formControlName="phone"></label><label>Email *<input type="email" formControlName="email"></label><label>City *<input formControlName="city"></label><label>State *<input formControlName="state"></label><label>PIN code *<input formControlName="pinCode"></label><label class="full">Address *<textarea rows="2" formControlName="address"></textarea></label></div></fieldset><fieldset><legend>Academic information</legend><div class="grid"><label>Previous school<input formControlName="previousSchool"></label><label>Previous class<input formControlName="previousClass"></label><label>Applying for class *<input formControlName="applyingClass" placeholder="e.g. 8A"></label><label>Previous percentage / grade<input type="number" formControlName="previousPercentage"></label><label>Board<input formControlName="board"></label><label>Academic year<input formControlName="academicYear"></label></div></fieldset><fieldset><legend>Parent / guardian information</legend><div class="grid"><label>Father name<input formControlName="fatherName"></label><label>Mother name<input formControlName="motherName"></label><label>Guardian name<input formControlName="guardianName"></label><label>Guardian phone<input formControlName="guardianPhone"></label><label>Guardian email<input type="email" formControlName="guardianEmail"></label><label>Occupation<input formControlName="guardianOccupation"></label></div></fieldset><fieldset><legend>Documents</legend><p class="muted">Document upload is reserved for a future backend-supported release.</p></fieldset><label class="declaration"><input type="checkbox" formControlName="declaration"> I confirm that the information provided is correct.</label><button class="submit" type="submit" [disabled]="loading">{{ loading ? 'Submitting...' : 'Submit application' }}</button></form></section></main>
  `,
  styles: [`
    :host{display:block;min-height:100vh}.admission-page{min-height:100vh;padding:32px 18px;background:linear-gradient(135deg,#eef4ff,#f8fafc)}.admission-card{width:min(900px,100%);margin:auto;padding:36px;background:#fff;border:1px solid #dbe4f0;border-radius:16px;box-shadow:0 18px 45px rgba(23,32,51,.1)}.back{border:0;background:none;color:#2563eb;font-weight:700;cursor:pointer}.eyebrow{margin:28px 0 4px;color:#2563eb;font-size:12px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}h1{margin:0;color:#172033}.muted{color:#64748b}fieldset{border:1px solid #e2e8f0;border-radius:10px;padding:20px;margin:22px 0}legend{padding:0 8px;color:#172033;font-weight:800}.grid{display:grid;grid-template-columns:1fr 1fr;gap:15px}label{display:grid;gap:6px;color:#334155;font-size:14px;font-weight:600}input,select,textarea{box-sizing:border-box;width:100%;padding:10px 11px;border:1px solid #cbd5e1;border-radius:7px;font:inherit}.full{grid-column:1/-1}.declaration{display:flex;grid-template-columns:auto 1fr;align-items:center;display:flex;gap:9px}.declaration input{width:auto}.submit{width:100%;margin-top:22px;padding:13px;border:0;border-radius:8px;background:#2563eb;color:#fff;font-weight:800;cursor:pointer}.submit:disabled{opacity:.6}.alert{padding:12px;border-radius:8px;margin-top:18px}.error{color:#b91c1c;background:#fef2f2}.success{color:#166534;background:#f0fdf4}@media(max-width:620px){.admission-card{padding:24px 16px}.grid{grid-template-columns:1fr}.full{grid-column:auto}}
  `]
})
export class StudentAdmissionComponent {
  loading=false; errorMessage=''; successMessage='';
  form: any;
  constructor(private formBuilder:FormBuilder, private apiService:ApiService, public router:Router, private changeDetectorRef:ChangeDetectorRef) {
    this.form=this.formBuilder.group({ fullName:['',Validators.required], dateOfBirth:['',Validators.required], gender:['',Validators.required], bloodGroup:[''], phone:['',[Validators.required,Validators.pattern(/^\d{10}$/)]], email:['',[Validators.required,Validators.email]], address:['',Validators.required], city:['',Validators.required], state:['',Validators.required], pinCode:['',[Validators.required,Validators.pattern(/^\d{6}$/)]], previousSchool:[''], previousClass:[''], applyingClass:['',Validators.required], previousPercentage:[null], board:[''], academicYear:['2026-27'], fatherName:[''], motherName:[''], guardianName:[''], guardianPhone:[''], guardianEmail:[''], guardianOccupation:[''], declaration:[false,Validators.requiredTrue] });
  }
  submit():void { this.errorMessage=''; this.successMessage=''; if(this.form.invalid){this.form.markAllAsTouched();this.errorMessage='Please complete all required fields and confirm the declaration.';return;} const value=this.form.getRawValue(); const names=value.fullName!.trim().split(/\s+/); this.loading=true; this.apiService.createStudentAdmission({ ...value, firstName:names.shift(), lastName:names.join(' ')||'Student' }).subscribe({ next:(response)=>{this.loading=false;const applicationNumber=response.data?.admission?.applicationId || '';this.successMessage=`Application submitted successfully. Status: PENDING${applicationNumber ? ` · Application: ${applicationNumber}` : ''}`;this.changeDetectorRef.markForCheck();}, error:error=>{this.loading=false;this.errorMessage=error.status===401?'Your session has expired. Please login again.':error.status===403?'You are not authorized to submit this application.':error.status===409?'You already have an admission application.':error.status===400?'Please check the information entered.':error.status>=500?'Server error. Please try again later.':'Unable to connect to the server.';this.changeDetectorRef.markForCheck();} }); }
}
